# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

inherit_gem:
  # rubocop-config-prettier: config/rubocop.yml # prettierの設定に合わせる
  rubocop-config-rufo: rubocop.yml # rufoの設定に合わせる

## rubocop 関連の gem を require します。
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

## 全体に適応する項目を定義します。ここで Exclude に設定したファイルは、チェック対象外になります。
AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"

Rails:
  Enabled: true

Layout/CommentIndentation:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

# An instance variable can be used when needed, but use let when possible.
RSpec/InstanceVariable:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

## 日本語コメントを許可します。
Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

# クラス/モジュールの入れ子の記載方法制限を無効化
Style/ClassAndModuleChildren:
  Enabled: false

# クラス/モジュールの説明記載必須を無効化
Style/Documentation:
  Enabled: false

# frozen_string_literalのマジックコメント推奨を無効化する。
# https://qiita.com/jnchito/items/e2687e2bf2f49411a1b4
Style/FrozenStringLiteralComment:
  Enabled: false

  # 文字列はダブルクォーテーションを使用
Style/StringLiterals:
  EnforcedStyle: double_quotes
